configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://aws-0-ap-southeast-1.pooler.supabase.com/postgres?user=postgres.ltsftcaydswjvyaeeamy&password=u8abA68M5fCGdZE7
